# Generated by Django 4.2.1 on 2023-05-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sides', '0002_side_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='side',
            name='price',
            field=models.IntegerField(),
        ),
    ]
