# Generated by Django 4.2.1 on 2023-05-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('offers', '0002_remove_offer_price_offer_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='drinks',
            field=models.ManyToManyField(blank=True, related_name='offers_drinks', to='product.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='pizzas',
            field=models.ManyToManyField(blank=True, related_name='offers_pizzas', to='product.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='sides',
            field=models.ManyToManyField(blank=True, related_name='offers_sides', to='product.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='total',
            field=models.IntegerField(default=True),
        ),
    ]
