# Generated by Django 4.2.1 on 2023-05-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizza_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.AddField(
            model_name='pizza',
            name='allergens',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pizza',
            name='large_price',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='medium_price',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='small_price',
            field=models.IntegerField(default=True),
        ),
    ]
