# Generated by Django 4.2.1 on 2023-05-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_remove_pizza_price_pizza_allergens_pizza_large_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzatype',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
