# Generated by Django 4.2.1 on 2023-05-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_user_profile'),
        ('user', '0006_rename_user_profile 2'),
    ]

    operations = [
    ]
